name: widget-server pipe

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      
      - name: Configure AWS Credentials
        id: configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
      
      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push the image to AWS ECR
        id: build-push-image
        run: |
          docker build -t widget-server:v4 .
          docker tag widget-server:v4 565393037139.dkr.ecr.us-east-2.amazonaws.com/rocketseat/widget-server:v4
          docker push 565393037139.dkr.ecr.us-east-2.amazonaws.com/rocketseat/widget-server:v4